// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.FRC2016.commands;


import org.usfirst.frc157.FRC2016.commands.AutoDriveSpeedForTime;
import org.usfirst.frc157.FRC2016.Robot;
import org.usfirst.frc157.FRC2016.RobotMap;
import org.usfirst.frc157.FRC2016.subsystems.Arm;
import org.usfirst.frc157.FRC2016.AnalogSelectSwitch.SwitchPosition;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousCommand extends CommandGroup 
{

    public AutonomousCommand() {
        
        requires(Robot.drive);
        
        SwitchPosition switchPosition = RobotMap.modeSelect.getPosition();
        
        System.out.println("Autonomous Switch: " + switchPosition);
        
        switch(switchPosition)
        {
            case POSITION_1:
                //drive straight forward low power
                //addSequential(new ArmShoulderMoveToAngle(Arm.Position.HOME.angle()));
                addSequential(new AutoDriveSpeedForTime(0.5, 0.5, 3.0));
                break;

            case POSITION_2:
                //drive straight forward high power 
                //addSequential(new ArmShoulderMoveToAngle(Arm.Position.HOME.angle()));
                addSequential(new AutoDriveSpeedForTime(0.75, 0.75, 3.0));
                break;

            case POSITION_3:
                //unimplemented
                break;

            case POSITION_4:
                //unimplemented
                break;

            case POSITION_5:
                //Do Nothing Autonomous mode
                break;
}
        

    }
}
