// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.FRC2016.commands;


import org.usfirst.frc.team157.robot.commands.DriveSpeedForTime;
import org.usfirst.frc157.FRC2016.Robot;
import org.usfirst.frc157.FRC2016.RobotMap;
import org.usfirst.frc157.FRC2016.AnalogSelectSwitch.SwitchPosition;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousCommand extends CommandGroup 
{

    public AutonomousCommand() {
        
        requires(Robot.drive);
        
        SwitchPosition switchPosition = RobotMap.modeSelect.getPosition();
        
        switch(switchPosition)
        {
            case POSITION_1:
                //drive straight forward , both wheels 
                addSequential(new AutoDriveMoveDistance(0.6, 0.6, 0.75));
                break;

            case POSITION_2:
                //unimplemented
                break;

            case POSITION_3:
                //unimplemented
                break;

            case POSITION_4:
                //unimplemented
                break;

            case POSITION_5:
                //Do Nothing Autonomous mode
                break;
}
        

    }
}
