// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.FRC2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc157.FRC2016.Robot;

/**
 *
 */
public class PrintIMUOutput extends Command {

	private String text;
     public PrintIMUOutput(String textToPrint) {
    	
    	text = textToPrint;
  
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	System.out.print(text);
//    	System.out.print(" H:");
//    	System.out.print(Robot.navigation.getHeading());
//    	System.out.print(" P:");
//    	System.out.print(Robot.navigation.getPitch());
//    	System.out.print(" R:");
//    	System.out.print(Robot.navigation.getRoll());
//    	System.out.print(" Y:");
//    	System.out.print(Robot.navigation.getYaw());
//    	System.out.println("-");
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
