// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.FRC2016;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveLeftDriveA;
    public static CANTalon driveRightDriveA;
    public static RobotDrive driveRobotDrive21;
    public static Encoder driveLeftEncoder;
    public static Encoder driveRightEncoder;
    public static CANTalon armShoulderMotor;
    public static Encoder armShoulderEncoder;
    public static CANTalon ballHandlerLeftShooter;
    public static CANTalon ballHandlerRightShooter;
    public static CANTalon ballHandlerBallRetriever;
    public static AnalogInput ballHandlerBallRangefinder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftDriveA = new CANTalon(0);
        LiveWindow.addActuator("Drive", "LeftDriveA", driveLeftDriveA);
        
        driveRightDriveA = new CANTalon(1);
        LiveWindow.addActuator("Drive", "RightDriveA", driveRightDriveA);
        
        driveRobotDrive21 = new RobotDrive(driveLeftDriveA, driveRightDriveA);
        
        driveRobotDrive21.setSafetyEnabled(true);
        driveRobotDrive21.setExpiration(0.1);
        driveRobotDrive21.setSensitivity(0.5);
        driveRobotDrive21.setMaxOutput(1.0);

        driveLeftEncoder = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("Drive", "LeftEncoder", driveLeftEncoder);
        driveLeftEncoder.setDistancePerPulse(1.0);
        driveLeftEncoder.setPIDSourceType(PIDSourceType.kRate);
        driveRightEncoder = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("Drive", "RightEncoder", driveRightEncoder);
        driveRightEncoder.setDistancePerPulse(1.0);
        driveRightEncoder.setPIDSourceType(PIDSourceType.kRate);
        armShoulderMotor = new CANTalon(2);
        LiveWindow.addActuator("Arm", "ShoulderMotor", armShoulderMotor);
        
        armShoulderEncoder = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("Arm", "ShoulderEncoder", armShoulderEncoder);
        armShoulderEncoder.setDistancePerPulse(1.0);
        armShoulderEncoder.setPIDSourceType(PIDSourceType.kRate);
        ballHandlerLeftShooter = new CANTalon(5);
        LiveWindow.addActuator("BallHandler", "LeftShooter", ballHandlerLeftShooter);
        
        ballHandlerRightShooter = new CANTalon(3);
        LiveWindow.addActuator("BallHandler", "RightShooter", ballHandlerRightShooter);
        
        ballHandlerBallRetriever = new CANTalon(4);
        LiveWindow.addActuator("BallHandler", "BallRetriever", ballHandlerBallRetriever);
        
        ballHandlerBallRangefinder = new AnalogInput(7);
        LiveWindow.addSensor("BallHandler", "BallRangefinder", ballHandlerBallRangefinder);
        
System.out.println("Robot INIT COMPLETE");
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
